main-und-profile
webml/sky-fitness-pro pull request #9
Opened 2022-12-04 13:28 UTC by Pavel545

я залил всё, в одном пуле

2022-12-04 13:58 UTC, Allgud commented on src/pages/profile/style.js
> +  font-family: "StratosSkyeng";
Как по мне, много повторяющегося кода в стилях. Может лучше в глобальном один раз прописать?

2022-12-04 14:03 UTC, Allgud commented on src/pages/profile/index.jsx
> +        <S.Buttom>Редактировать логин</S.Buttom>
Здесь опечатка? И я эти кнопки по отдельному заданию делал. В UI Kit будут когда сольют все ПР

2022-12-04 14:46 UTC, Allgud approved these changes
Пару комментов оставил. Но исправления лучше вносить когда все ПР зальют. Стили глобальные сделаны. Кнопки сделаны.

2022-12-05 12:43 UTC, Pavel545 commented on src/pages/profile/style.js
> +  font-family: "StratosSkyeng";
угу, щяс шрифт скинул в глобал, вроде больше нечего так закономерно не повторяется, и к тому же он вроде не работает а в гугле его нет, иииииии его может в курсовой поскать как думаете?

2022-12-05 12:44 UTC, Pavel545 commented on src/pages/profile/index.jsx
> +        <S.Buttom>Редактировать логин</S.Buttom>
ну чтобы пробелов не было. а так можно на этапе общего тестирования, лии же когда будем прописывать функционал быстренько заменить компонентом.

2022-12-05 14:51 UTC, webml requested changes

2022-12-05 14:51 UTC, webml commented on src/components/Сourses/style.js
> +};
Может лучше в стиль прокидывать фон для курса через пропсы? Если курсов станет больше, придётся лезть в код, чтобы добавлять новые фоны

2022-12-05 15:27 UTC, Allgud commented on src/pages/profile/style.js
> +  font-family: "StratosSkyeng";
Я из какой-то предыдущей работы его взял.

2022-12-05 17:32 UTC, Pavel545 commented on src/components/Сourses/style.js
> +};
готово,

2022-12-05 17:45 UTC, webml approved these changes

2022-12-06 07:38 UTC, closed without merging